<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Client;
use AppBundle\Entity\ClientAddress;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends ServiceEntityRepository
{
    public function __construct(RegistryInterface  $registry)
    {
        parent::__construct($registry, Client::class);
    }
}
