<?php
namespace AppBundle\Repository;
use AppBundle\Entity\Client;
use AppBundle\Entity\ClientAddress;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\ORM\EntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;


/**
 * ClientAddressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientAddressRepository extends ServiceEntityRepository
{
    public function __construct(RegistryInterface  $registry)
    {
       parent::__construct($registry, ClientAddress::class);
    }
    public function findAddressForClient($addressId, Client $client)
    {
        return $this->findOneBy(['id' => $addressId, 'client' => $client]);
    }

}
