<?php

namespace AppBundle\Repository;
use AppBundle\Entity\ClientOrder;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * ClientOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientOrderRepository extends ServiceEntityRepository
{
    public function __construct(RegistryInterface  $registry)
    {
        parent::__construct($registry, ClientOrder::class);
    }
}
