<?php

namespace AppBundle\Repository;
use AppBundle\Entity\ShopperAssignment;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * ShopperAssignmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopperAssignmentRepository extends ServiceEntityRepository
{
    public function __construct(RegistryInterface  $registry)
    {
        parent::__construct($registry, ShopperAssignment::class);
    }
}
